### ISSUE TITLE
Looking good but can't be tested fully without keyboard support

### ISSUE THREAD

**Issue by ExileFox** [CoolCreasu/RayCastVehicle#1]

**Comment by CoolCreasu** [comment]
- [ ] It should support keyboard, this repository is mostly made just so i have a backup of the files from the tutorial i followed.

These are the keys:

W: Accelerate
S: Brake
Spacebar: Handbrake
A & D: steering

P, L: gear switching

**Comment by ExileFox** [comment]
I could not find where they were defined, now it makes sense why the
vehicle wouldn't move. Thanks for the quick reply.
